Update flatpak-guide.md
tchx84/sugarapp pull request #12
Opened 2023-03-27 15:30 UTC by Ashley0703

Add "install SDK" to make it easier in the step of  packaging the applications with Flatpak

2023-03-27 16:49 UTC, tchx84 requested changes
Please add it to the section I mentioned on matrix :pray: 

![Screenshot from 2023-03-27 12-49-14](https://user-images.githubusercontent.com/481418/228010103-ea004a09-427a-43cb-a0de-a822457cdb2b.png)

2023-03-27 17:37 UTC, Ashley0703 commented
My bad. I thought "step 2" means “Porting an application with sugarapp” section.

2023-03-27 17:42 UTC, Ashley0703 commented
Updated.

2024-02-28 14:06 UTC, tchx84 approved these changes

2024-02-28 14:07 UTC, closed without merging