add more documentation about validation after building app with flatpak
tchx84/sugarapp pull request #3
Opened 2019-12-26 14:43 UTC by pidddgy

This would have helped me a lot and hopefully this will be useful to other developers.

2019-12-27 23:52 UTC, tchx84 requested changes
Thanks for the clarifications, a few comments.

2019-12-27 23:52 UTC, tchx84 commented on flatpak-guide.md
> +    If appstream-util validate is not running, you can also try `flatpak run org.freedesktop.appstream-glib validate` as documented in https://github.com/flathub/flathub/wiki/AppData-Guidelines#use-f
Better to link the document than showing the whole URL. e.g. "as described in the [flathub documentation](https://github.com/flathub/flathub/wiki/AppData-Guidelines#use-flathubs-appstream-util)."

2019-12-27 23:52 UTC, tchx84 commented on flatpak-guide.md
> +    If the validate command is having trouble reading the appdata XML file, you can try using `cat` to read the xml file, pipe the result into a local directory, and change the path that you pass int
Can you describe the scenario where this was necessary?

2019-12-28 00:34 UTC, pidddgy commented
After thinking about it for a while, I think it would be best if we closed this PR - `flatpak run org.freedesktop.appstream-glib validate` was telling me things were okay when they weren't for some reason (hence why you had to return my task so many times, lol). I tried to use that because appstream-util wasn't installed and that alternative command was what I stumbled across first and I stupidly decided to use that instead. The workaround I had to do with `cat` and piping was also probably due to the alternative command as I just tested it with appstream-util  and it seems to be working fine.

 I think it would be better if we just included instructions on how to install appstream-util (it's just a simple apt-get install)

2019-12-28 00:34 UTC, closed without merging